CREATE DATABASE IF NOT EXISTS DB_TROCAVENDA;

USE DB_TROCAVENDA;

CREATE TABLE IF NOT EXISTS TB_ESTADOS (
    EST_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
    EST_ESTADO char(2) NOT NULL,
    CONSTRAINT PRIMARY KEY (EST_ID)
);

CREATE TABLE IF NOT EXISTS TB_USUARIOS (
  USU_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  USU_NOME varchar(90) NOT NULL,
  USU_EMAIL varchar(150) NOT NULL,
  USU_LOGIN varchar(30) NOT NULL,
  USU_SENHA varchar(30) NOT NULL,
  USU_DATACAD datetime NOT NULL,
  USU_EST_ID TINYINT UNSIGNED NOT NULL,
  USU_CIDADE varchar(90) NOT NULL,
  CONSTRAINT PRIMARY KEY (USU_ID),
  CONSTRAINT FK_EST_USU FOREIGN KEY(USU_EST_ID) REFERENCES TB_ESTADOS(EST_ID)
);


CREATE TABLE IF NOT EXISTS TB_PRODUTOSDOSUSUARIOS (
  PDU_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PDU_USU_ID INT UNSIGNED NOT NULL ,
  PDU_TELEFONE varchar(12) NOT NULL,
  PDU_WHATSAPP varchar(12) NULL,
  PDU_NOME varchar(90) NOT NULL,
  PDU_DESCRICAO varchar(500) NULL,
  PDU_FOTO varchar(300) NULL,
  PDU_QUANT SMALLINT UNSIGNED,
  PDU_PRECO DOUBLE UNSIGNED NOT NULL ,
  PDU_VENDIDO boolean NULL,
  PDU_DATACAD datetime NOT NULL,
  CONSTRAINT PRIMARY KEY (PDU_ID),
  CONSTRAINT FK_USU_PDU FOREIGN KEY(PDU_USU_ID) REFERENCES TB_USUARIOS(USU_ID)
);


INSERT INTO TB_ESTADOS
	(EST_ESTADO)
VALUES
	('RN'),('AC'),('AL'),('AM'),('AP'),('BA'),('CE'),('DF'),('ES'),('GO'),('MA'),('MG'),('MT'),('MS'),('PA'),('PB'),('PE'),('PI'),('PR'),('RO'),('RJ'),('RR'),('RS'),('SP'),('SC'),('SE'),('TO');

INSERT INTO TB_USUARIOS
	(USU_NOME, USU_EMAIL, USU_LOGIN, USU_SENHA, USU_EST_ID, USU_CIDADE, USU_DATACAD)
VALUES 
	('MARIA DA SILVA','ADMIN@RN.COM.BR', 'ADMIN', '12345', '1', 'NATAL', NOW()),
    ('JOAO DA SILVA', 'JOAOSILVA@RN.COM.BR', 'JOAOSILVA', 'QWERT', 'NATAL', NOW());

INSERT INTO TB_PRODUTOSDOSUSUARIOS
	(PDU_USU_ID, PDU_NOME, PDU_TELEFONE, PDU_WHATSAPP, PDU_DESCRICAO, PDU_QUANT, PDU_PRECO, PDU_FOTO, PDU_DATACAD)
VALUES 
	(1,'TV','849879-9879', '849879-9879', 'TV Samsung 40 pol. em bom estado', 1, 700.00, 'assets/img/tv.jpg',NOW()),
    (2,'Sapato Feminino','849879-9879', '849879-9879', 'Salto Alto Vizzano preto 35', 1, 30.00, 'assets/img/sapatos.jpg', NOW()),
    (2,'Sapato Infantil','849879-9879', '849879-9879', 'Sapato de Bebe ', 1, 15.00, 'assets/img/sapatosbebe.jpg', NOW());
    
